@extends('layouts.basic')

@section('page-title', 'Terms & Conditions')
@section('og:title', 'Terms & Conditions')

@section('pageContent')
    <h1>Age and Peace Terms &amp; Conditions</h1>

    <p>Please read these Terms and Conditions carefully before using this Website.</p>

    <h2>Terms and Conditions</h2>
    <p>The Website and its Content is owned by Inovage, Inc (“Company”, “we”, or “us”). The term “you” refers to the user or viewer of ageandpeace.com (“Website”).</p>
    <p>Please read these Terms and Conditions (“T&C”) carefully. We reserve the right to change these Terms and Conditions on the Website at any time without notice, and by using the Website and its Content you are agreeing to the T&C as they appear, whether or not you have read them. If you do not agree with these T&C, please do not use our Website or its Content.</p>

    <h2>Website Use and Consent</h2>
    <p>The words, design, layout, graphics, photos, images, information, materials, documents, data, databases and all other information and intellectual property accessible on or through this Website (“Content”) is our property and is protected by United States intellectual property laws.</p>
    <p>If you have purchased a service, program, product or subscription or otherwise entered into a separate agreement with us, you will also be subject to the terms of that agreement or those terms of use, which shall prevail in the event of a conflict. Online purchases have additional terms of use relating to the transaction.</p>
    <p>By accessing or using this Website and its Content, you represent and warrant that you are at least 18 years old and that you agree to and to abide by these T&C. Any registration by, use of or access to the Website and its Content by anyone under age 18 is unauthorized, unlicensed and in violation of these T&C.</p>

    <h2>Intellectual Property Rights</h2>
    <p><strong>Our Limited License to You.</strong> This Website and its Content is property solely owned by us and/or our affiliates or licensors, unless otherwise noted, and it is protected by copyright, trademark, and other intellectual property laws.</p>
    <p>If you view, purchase or access our Website or any of its Content, you will be considered our Licensee. For the avoidance of doubt, you are granted a revocable, non-transferable license for personal, non-commercial use only, limited to you only.</p>

    <p><strong>When you purchase or access our Website or any of its Content, you agree that:</strong></p>
    <ul>
        <li><strong>You will not copy, duplicate or steal our Website or Content. You understand that doing anything with our Website or its Content that is contrary to these T&C and the limited license we are providing to you herein is considered theft, and we reserve our right to prosecute theft to the full extent of the law.</strong></li>
        <li><strong>You are permitted from time to time to download and/or print one copy of individual pages of the Website or its Content, for your personal, non-commercial use, provided that you give us full attribution and credit by name, keep intact all copyright, trademark and other proprietary notices and, if used electronically, you must include the link back to the Website page from which the Content was obtained.</strong></li>
        <li><strong>You may not in any way at any time use, copy, adapt, imply or represent that our Website or its Content is yours or created by you. By downloading, printing, or otherwise using our Website Content for personal use you in no way assume any ownership rights of the Content – it is still our property.</strong></li>
        <li><strong>You must receive our written permission before using any of our Website Content for your own business use or before sharing with others. This means that you may not modify, copy, reproduce, republish, upload, post, transmit, translate, sell, market, create derivative works, exploit, or distribute in any manner or medium (including by email, website, link or any other electronic means) any Website Content because that is considered stealing our work.</strong></li>
        <li><strong>We are granting you a limited license to enjoy our Website and its Content for your own personal use, not for your own business/commercial use or in any that earns you money, unless we give you written permission that you may do so.</strong></li>
    </ul>

    <p><strong>As a Licensee, you understand and acknowledge that this Website and its Content have been developed or obtained by us through the investment of significant time, effort and expense, and that this Website and its Content are valuable, special and unique assets of ours which need to be protected from improper and unauthorized use. We clearly state that you may not use this Website or its Content in a manner that constitutes an infringement of our rights or that has not been authorized by us.</strong></p>
    <p>The trademarks and logos displayed on our Website or its Content are trademarks belonging to us, unless otherwise indicated. Any use including framing, meta tags or other text utilizing these trademarks, or other trademarks displayed, is strictly prohibited without our written permission.</p>
    <p>All rights not expressly granted in these terms or any express written license, are reserved by us.</p>
    <p><strong>Your License to Us.</strong> By posting or submitting any material on or through our Website such as comments, posts, photos, images or videos or other contributions, you are representing that you are the owner of all such materials and you are at least 18 years old.</p>
    <p>When you voluntarily submit to us or post any comment, photo, image, video or any other submission for use on or through our Website, you are granting us, and anyone authorized by us, consent to make it part of our current or future Website and its Content. This right includes granting us proprietary rights or intellectual property rights under any relevant jurisdiction without any further permission from you or compensation by us to you.  Your rights regarding this personal information can be found in our Privacy Policy.</p>
    <p>You acknowledge that we have the right but not the obligation to use any contributions from you and that we may elect to cease the use of any such contributions on our Website or in our Content at any time for any reason.</p>

    <h2>Request for Permission to Use Content</h2>
    <p>Any request for written permission to use our Content, or any other intellectual property or property belonging to us, should be made BEFORE you wish to use the Content by completing the “Contact Us” form on this Website, or by sending an e-mail to {!! mailto('help@ageandpeace.com') !!}.</p>
    <p><strong>We very clearly state that you may not use any Content in any way that is contrary to these T&C unless we have given you specific written permission to do so. If you are granted permission by us, you agree to use the specific Content that we allow and ONLY in the ways for which we have given you our written permission. If you choose to use the Content in ways that we do not specifically give you written permission, you agree now that you will be treated as if you had copied, duplicated and/or stolen such Content from us, and you consent to immediately stop using such Content and to take whatever actions as we may request and by the methods and in the time frame that we prescribe to protect our intellectual property and ownership rights in our Website and its Content.</strong></p>

    <h2>Personal Responsibility and Assumption of Risk</h2>
    <p>As a Licensee, you agree that you are using your own judgment in using our Website and its Content and you agree that you are doing so at your own risk. You agree and understand that you assume all risks and no results are guaranteed in any way related to this Website and/or any of its Content. This Website and its Content are merely to provide you with education and tools to help you make your own decisions for yourself. You are solely responsible for your actions, decisions and results based on the use, misuse or non-use of this Website or any of its Content.</p>

    <h2>Disclaimer</h2>
    <p>Our Website and its Content are for informational and educational purposes only. To the fullest extent permitted by law, we expressly exclude any liability for any direct, indirect or consequential loss or damage incurred by you or others in connection with our Website and its Content, including without limitation any liability for any accidents, delays, injuries, harm, loss, damage, death, lost profits, personal or business interruptions, misapplication of information, physical or mental disease, condition or issue, physical, mental, emotional, or spiritual injury or harm, loss of income or revenue, loss of business, loss of profits or contracts, anticipated savings, loss of data, loss of goodwill, wasted time and for any other loss or damage of any kind, however and whether caused by negligence, breach of contract, or otherwise, even if foreseeable. You specifically acknowledge and agree that we are not liable for any defamatory, offensive or illegal conduct of any other Website participant or user, including you.</p>

    <h3>Medical Disclaimer</h3>
    <p>This Website and its Content are not to be perceived as or relied upon in any way as medical advice or mental health advice. The information provided through our Website or Content is not intended to be a substitute for professional medical advice, diagnosis or treatment that can be provided by your own physician, nurse practitioner, physician assistant, therapist, counselor, mental health practitioner, licensed dietitian or nutritionist, member of the clergy, or any other licensed or registered health care professional. Do not disregard professional medical advice or delay seeking professional advice because of information you have read on this Website, its Content, or received from us. Do not stop taking any medications without speaking to your physician, nurse practitioner, physician assistant, mental health provider or other healthcare professional. If you have or suspect that you have a medical or mental health issue, contact your own health care provider promptly.  We are not providing health care, medical or nutrition therapy services or attempting to diagnose, treat, prevent or cure in any manner whatsoever any physical ailment, or any mental or emotional issue, disease or condition. We are not giving medical, psychological, or religious advice whatsoever.</p>
    <p><strong>Legal and Financial Disclaimer.</strong> This Website and its Content are not to be perceived or relied upon in any way as business, financial or legal advice. The information provided through our Website and its Content is not intended to be a substitute for professional advice that can be provided by your own accountant, lawyer, or financial advisor. We are not giving financial or legal advice in any way. You are hereby advised to consult with your own accountant, lawyer or financial advisor for any and all questions and concerns you have regarding your own income and taxes pertaining to your specific financial and/or legal situation. You agree that we are not responsible for your earnings, the success or failure of your business decisions, the increase or decrease of your finances or income level, or any other result of any kind that you may have as a result of information presented to you through our Website or its Content. You are solely responsible for your results.</p>
    <p><strong>Earnings Disclaimer.</strong> You acknowledge that we have not and do not make any representations as to the health physical, mental, emotional, spiritual or health benefits, future income, expenses, or potential profitability or loss of any kind that may be derived as a result of your use of this Website or its Content. We cannot and do not guarantee that you will attain a particular result, positive or negative, financial or otherwise, through the use of our Website or its Content and you accept and understand that results differ for each individual. We also expressly disclaim responsibility in any way for the choices, actions, results, use, misuse or non-use of the information provided or obtained through the use of our Website or its Content. You agree that your results are strictly your own and we are not liable or responsible in any way for your results.</p>
    <p><strong>Warranties Disclaimer.</strong> WE MAKE NO WARRANTIES AS TO OUR WEBSITE OR ITS CONTENT. YOU AGREE THAT OUR WEBSITE AND ITS CONTENTS ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE WEBSITE OR ITS CONTENT WILL BE FUNCTIONAL, UNINTERRUPTED, CORRECT, COMPLETE, APPROPRIATE, OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT ANY PART OF THE WEBSITE, CONTENT ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF OUR WEBSITE OR ITS CONTENT OR ON THIRD-PARTY WEBSITES IN TERMS OF THEIR CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY OR OTHERWISE.</p>
    <p><strong>Technology Disclaimer.</strong> We try to ensure that the availability and delivery of our Website and its Content is uninterrupted and error-free. However, we cannot guarantee that your access will not be suspended or restricted from time to time, including to allow for repairs, maintenance or updates, although, of course, we will try to limit the frequency and duration of suspension or restriction. To the fullest extent permitted by law, we will be not be liable to you for damages or refunds, or for any other recourse, should our Website or its Content become unavailable or access to the them becomes slow or incomplete due to any reason, such as system back-up procedures, internet traffic volume, upgrades, overload of requests to the servers, general network failures or delays, or any other cause which may from time to time make our Website or its Content inaccessible to you.</p>
    <p><strong>Errors and Omissions.</strong> We make no warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information on our Website or its Content. Every effort has been made to present you with the most accurate, up-to-date information, but because the nature of scientific research is constantly evolving, we cannot be held responsible or accountable for the accuracy of our content. We assume no liability for errors or omissions on the Website, its Content, or in other information referenced by or linked to the site. You acknowledge that such information may contain inaccuracies or errors to the fullest extent permitted by law.</p>
    <p><strong>Links to Other Websites.</strong> We may provide links and pointers to other websites maintained by third parties which may take you outside of our Website or its Content. These links are provided for your convenience and the inclusion of any link in our Website or its Content to any other website does not imply our endorsement, sponsorship, or approval of that website or its owner. We do not endorse and we are not responsible for the views, opinions, facts, advice, statements, errors or omissions provided by external resources referenced in our Website or its Content, or their accuracy or reliability. We have no control over the contents or functionality of those websites and so we accept no responsibility for any loss, damage, or otherwise that may arise from your use of them. It is your responsibility to review the terms and conditions and privacy policies of those linked websites to confirm that you understand and agree with those policies.</p>
    <p><strong>Limitations on Linking and Framing.</strong> You may establish a hypertext link to our Website or Content so long as the link does not state or imply any sponsorship, endorsement, or ownership with our Website or Content and does not state or imply that we are have sponsored, endorsed or have ownership rights in your website. However, you may not frame or inline link our Content without our written permission.</p>
    <p>By purchasing and/or using our Website and its Content in any way or for any reason, you also implicitly agree to our full Disclaimer which may be found on this Website.</p>

    <h2>Indemnification, Limitation of Liability and Release of Claims</h2>
    <p><strong>Indemnification.</strong> You agree at all times to defend, indemnify and hold harmless our Company, as well as any of our affiliates, agents, contractors, officers, directors, shareholders, employees, joint venture partners, successors, transferees, assignees, and licensees, as applicable, from and against any and all claims, causes of action, damages, liabilities, costs and expenses, including legal fees and expenses, arising out of or related to our Website, its Content or your breach of any obligation, warranty, representation or covenant set forth in these T&C or in any other agreement with us.</p>
    <p><strong>Limitation of Liability.</strong> We will not be held responsible or liable in any way for the information, products or materials that you request or receive through or on our Website and its Content. We do not assume liability for accidents, delays, injuries, harm, loss, damage, death, lost profits, personal or business interruptions, misapplication of information, physical or mental disease, condition or issue, or otherwise, due to any act or default of anyone or any business, whether owners, staff, agents, joint venture partners, contractors, vendors, affiliates or otherwise, affiliated with us.  We do not assume liability for any owners, staff, agents, joint venture partners, contractors, vendors, affiliates or otherwise who is engaged in rendering our Website or its Content, or in any way or in any location. In the event that you use our Website and its Content or any other information provided by us or affiliated with us, we assume no responsibility.</p>
    <p><strong>Release of Claims.</strong> In no event will we be liable to any party for any type of direct, indirect, special, incidental, equitable or consequential damages for any use of or reliance on our Website and its Content, or on those affiliated with us in any way, and you hereby release us from any and all claims; including, without limitation, those related to lost profits, personal or business interruptions, personal injuries, accidents, misapplication of information, or any other loss, physical or mental disease, condition or issue, or otherwise, even if we are expressly advised of the possibility of such damages or difficulties.</p>

    <h2>Your Conduct</h2>
    <p>You are agreeing that you will not use our Website or its Conduct in any way that causes or is likely to cause the Website, Content, or access to them to be interrupted, damaged or impaired in any way. You understand that you are solely responsible for all electronic communications and content sent from your computer to this Website and its Content and to us.</p>
    <p>You agree to only purchase goods or services for yourself or for another person for whom you are legally permitted to do so or for whom you have obtained the express consent to provide their name, address, method of payment, credit card number, and billing information.</p>
    <p>You agree to be financially responsible for all purchases made by you or someone acting on your behalf through the Website or its Content. You agree to use the Website and its Content for legitimate, non-commercial purposes only and not for speculative, false, fraudulent, or illegal purposes.</p>
    <p>You must use the Website and its Content for lawful purposes only.  You agree that you will not use the Website or its Content in any of the following ways:</p>
    <ul>
        <li>For fraudulent purposes or in connection with a criminal offense or otherwise carry out any unlawful activity</li>
        <li>To send, use or re-use any material that is illegal, offensive, abusive, indecent, harmful, defamatory, obscene or menacing, threatening, objectionable, invasive of privacy, in breach of confidence, infringing of any intellectual property rights, or that may otherwise may injure others</li>
        <li>To send, negatively impact, or infect our Website or its Content with software viruses or any other harmful or similar computer code designed to adversely affect the operation of any computer software or hardware, commercial solicitation, chain letters, mass mailings or any spam, whether intended or not</li>
        <li>To cause annoyance, inconvenience or needless anxiety</li>
        <li>To impersonate any third party or otherwise mislead as to the origin of your contributions</li>
        <li>To reproduce, duplicate, copy or resell any part of our Website or its Content in a way that is not in compliance with these T&C or any other agreement with us.</li>
    </ul>

    <h2>Online Commerce</h2>
    <p>Certain sections of the Website or its Content may allow you to make purchases from us or from other merchants. If you make a purchase from us on or through our Website or its Content, all information obtained during your purchase or transaction and all of the information that you give as part of the transaction, such as your name, address, method of payment, credit card number, and billing information, may be collected by both us, the merchant, and our payment processing company.  Please review our Privacy Policy for how we comply with securing your personal data.</p>
    <p>Your participation, correspondence or business dealings with any affiliate, individual or company found on or through our Website, all purchase terms, conditions, representations or warranties associated with payment, refunds, and/or delivery related to your purchase, are solely between you and the merchant. You agree that we shall not be responsible or liable for any loss, damage, refunds, or other matters of any sort that incurred as the result of such dealings with a merchant.</p>
    <p>Payment processing companies and merchants may have privacy and data collection practices that are different from ours. We have no responsibility or liability for these independent policies of the payment processing companies and merchants. In addition, when you make certain purchases through our Website or its Content, you may be subject to the additional terms and conditions of a payment processing company, merchant or us that specifically apply to your purchase. For more information regarding a merchant and its terms and conditions that may apply, visit that merchant’s Website and click on its information links or contact the Merchant directly.</p>
    <p>You release us, our affiliates, our payment processing company, and merchants from any damages that you incur, and agree not to assert any claims against us or them, arising from your purchase through or use of our Website or its Content.

    <h2>Termination</h2>
    <p>We reserve the right in our sole discretion to refuse or terminate your access to the Website and its Content, in full or in part, at any time without notice. In the event of cancellation or termination, you are no longer authorized to access the part of the Website or Content affected by such cancellation or termination. The restrictions imposed on you in these T&C with respect to the Website and its Content will still apply now and in the future, even after termination by you or us.</p>
    <p>If you have any questions about these T&C, please contact us at {!! mailto('info@ageandpeace.com') !!}.</p>

    <p>Last Updated:  July 2019</p>

@endsection

